### ISSUE TITLE
Propose technology and set up basics

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-app#1]
There were already some discussions about the choice of technology of this project, which could either be a web app or a native Android app. Please propose the most suitable choice of technology and set up the repository accordingly.

**Comment by niranjan94** [comment]
> Based on the discussions that took place on Gitter at [fossasia/open-event](https://gitter.im/fossasia/open-event?at=57aecd4f625cb3d845432e51) on Aug 13.

- We should support iOS and Android platforms
- Full native iOS and android apps are not feasible at this moment since we do not have iOS developers on our team yet
- A best option for us would be a PWA ([Progressive web application](https://developers.google.com/web/progressive-web-apps/)) or a Hybrid application with Cordova or the likes of it.

Initially suggested by mananwason, [Ionic Framework](http://ionicframework.com/) seems to suit our needs quite well.

- Cross-platform apps that support Android and iOS
- Apps are built using web technologies like HTML, CSS, and javascript which most of the team is already familiar with and are easy to learn for beginners.
- It's Free and open sourced framework

@mariobehling I also suggest we go with Ionic framework

**Comment by mariobehling** [comment]
@niranjan94 Sounds good. So, let's go with Ionic then. Could you add the necessary files to start and the setup info to the Readme.md, please?

**Comment by niranjan94** [comment]
Will do it right away.
