### ISSUE TITLE
Can't Proceed After Step 3 Of Create New Event .

### ISSUE THREAD

**Issue by ankush-01** [fossasia/open-event-orga-app#1404]
Current Behaviour :
   can't proceed after step 3rd of create new activity even all field is filled.
   Their is no error "Why event is not created".

Expected Behaviour :
   event is generated when user filled out all details and click on CREATE button.
   Error should be displayed like by  Toast Or TextInputLayout Error.

![bug](https://user-images.githubusercontent.com/33266550/49332207-9e377b80-f55d-11e8-8a75-0b4a2d437e7d.jpg)

**Comment by ShridharGoel** [comment]
@iamareebjamal Experiencing this problem even while using a verified email created using https://api.eventyay.com as the base URL.

**Comment by iamareebjamal** [comment]
Is the email verified?

**Comment by iamareebjamal** [comment]
Also, use open-event-api-dev.herokuapp.com as api.eventyay.com is production API

**Comment by ShridharGoel** [comment]
Yes it's verified.

**Comment by ShridharGoel** [comment]
Found the error when I saw the logs while trying to create an event through the app.

{"errors": [{"status": 403, "source": {"source": "/data/attributes/is-ticketing-enabled"}, "title": "Access Forbidden", "detail": "Ticketing is not enabled in the system"}], "jsonapi": {"version": "1.0"}}

Earlier I was checking the option "Use Ticketing System". Now, I tried by entering some random URL in the Ticket Url box instead of checking that option and the event was created successfully.

**Comment by iamareebjamal** [comment]
Yes, so the global ticketing system might not be enabled. I'll give you an API endpoint to verify your mail on dev server

**Comment by iamareebjamal** [comment]
POST `/v1/auth/verify-email`

```
{
  "data": {
    "token": "your token"
  }
}
```

**Comment by iamareebjamal** [comment]
Try again. Working fine for me. To solve this issue. Please display the error to the user

**Comment by ShridharGoel** [comment]
Okay I'll do it once #1411 is merged to avoid conflicts.

**Comment by ShridharGoel** [comment]
Okay I'll do it once #1411 is merged to avoid conflicts.

**Comment by iamareebjamal** [comment]
How will it cause conflicts?

**Comment by ShridharGoel** [comment]
Certain changes might be required in CreateEventViewModel to fix this issue also so I thought that it might cause merge conflicts, but now I realise that it wouldn't.
