### ISSUE TITLE
Implement support for json-api 

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-app#161]
The Open Event Server is moving towards a new API as per the [json-api specification](http://jsonapi.org/). Hence all the client apps need to support the same. 

You can checkout some of the Android client libraries that you can use to easily consume the API at http://jsonapi.org/implementations/#client-libraries-android.

**Comment by mejariamol** [comment]
@iamareebjamal are you working on this?

**Comment by iamareebjamal** [comment]
@mejariamol I don't think any one person will be sufficient for this. And check out this -> https://github.com/fossasia/open-event-android/issues/1680

We should be working with Android app team to develop a common solution. I have been implementing test apps mocking the json api. But having difficulties due to all libraries requiring to extend some classes. I'm currently analyzing the code of Open Source libraries to see any possible workarounds

**Comment by iamareebjamal** [comment]
https://github.com/iamareebjamal/open-event-android-sdk
