### ISSUE TITLE
Test performance of the app with large event

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#185]
Currently we are not aware of a performance of the app with large event which will be having large attendees.

So approximate workaround will be
- Make a test event which will be having large attendees (1000+)
- Check the performance for attendees page, qr scan
- Create issues accordingly

This can be taken up by all devs on board.

@iamareebjamal please label it `high-priority`, `open-for-all`

**Comment by iamareebjamal** [comment]
While I'm working on DB. I'll give you a tip. No need to create so much hassle (well you can if you want to do real testing). We have created the application in a modular way so you can just create a new EventService and return mock JSON with 1000 attendees, and it will work!

**Comment by iamareebjamal** [comment]
This should be first principle and then we can test the actual server response, but the test is for the app, so the only think, that will not be emulated here will be the response time for getting all attendees (which is actually not our problem)

**Comment by mejariamol** [comment]
@mariobehling @niranjan94 @iamareebjamal 

I tested the app for an event with **1089** attendees with average down speed of 120 KB/s. 

Currently the app loads all the attendees at a time and it took **13 sec** (average) to display 1089 attendees on the screen after opening event detail screen of the event. Although this will be one time that is for first time only. Once all the attendees are loaded and saved in database all the functions are handled efficiently. functions here means - toggling attendee check in direct and via qr scan, displaying attendees list.

So? do we need to decrease initial loading time or is it acceptable?

**Comment by iamareebjamal** [comment]
This initial loading time you are talking about, if I am correct, is because of the data loading from the network. In which case, we can't really do anything about it. Secondly, please try on the database version to see how it plays. There will be a difference in speed of retrieval from the in-memory cache that was being used till now

**Comment by mejariamol** [comment]
>because of the data loading from the network. In which case, we can't really do anything about it

**I didn't get the need of loading all the attendees locally.**

We don't have to load all the attendees locally.

### For attendees list
- attendees can be loaded by stocks according to viewport requirement. And shall be stored in **cache** only
- searching attendees by name should be implemented on api
- toggling check in is already being called on api

### For ticket and attendees stats
- This also need to be shifted to server.
- Server should have a stats endpoint which will provide stats accordingly.

**So what exactly use of storing all the attendees locally?**

Petrixdroid is also following same approach. Doing all the functions on server.

@niranjan94 @mariobehling @iamareebjamal  what is your opinion?

**Comment by iamareebjamal** [comment]
You can't scan by QR then, because you won't have the complete set of attendees. And we simply can't do everything on the server as it does not have API for everything

Besides, cache was to be removed once database is implemented, so it is not there anymore

**Comment by mejariamol** [comment]
> And we simply can't do everything on the server as it does not have API for everything

new api is being created hence these endpoints can be added which is **really necessary**. 

>cache was to be removed once database is implemented, so it is not there anymore

I don't see point in storing attendees in database.

**Comment by iamareebjamal** [comment]
@mejariamol I'll repeat, you can't scan by QR then because you won't have the complete set of attendees.

Secondly, searching from server every time is the worst possible design pattern on native applications. Just imagine organizer waiting for the search to finish when you have all the data to perform search locally. 

Thirdly, I never said, server should not implement it, just that we should not sit idle waiting for the implementation to happen. Furthermore, the new API is being created, that doesn't mean we can just add it in one go.

Lastly, our app should be offline ready. We'll use JobScheduler to queue the network requests and mark the models in the database transient, and once the network comes back online, we won't be able to do this if we don't save models in database

**Comment by niranjan94** [comment]
- The app needs to be offline ready - **Very important**.
   - Just imagine a big a event with a lot of attendee (In the order of 1000s) and network fails or the network is slow (Happens all the time in public wifi). Imagine the mess at the entrance when each attendee is waiting for his ticket to be scanned and verified. 
  - So, for this, I believe the best way is to cache the attendees locally in one go and sync it up with the server in the background so that even if there is a lack of network, it does not cause the organizer to go mad
- Stats endpoint can be provided. No issues.

@mejariamol @iamareebjamal

**Comment by mejariamol** [comment]
Okay. So currently attendees are loaded only when the concerned event is open. I think we should start loading all data in background once user logs in. These can be made in steps. for example 
1. All the events will be loaded and saved
2. All the attendees of events will be loaded and saved
3. Till then we can show the data from local storage only which is loaded with progressbar and can implement flag system for each event if its complete data is loaded. once it is done we can show all the data.

**Comment by iamareebjamal** [comment]
This is counter intuitive to the flow of the app. If there are past events with 1000s of attendees, we might be unnecessarily pulling data and filling up the database where the user never even opens the event. I don't think this should be done. Attendees should only be loaded on demand

**Comment by niranjan94** [comment]
> All the events will be loaded and saved

The basic details of the event (name & dates for example) could be loaded and cached

> All the attendees of events will be loaded and saved

Not for all events. Only when the attendee list is opened for the first time

**Comment by iamareebjamal** [comment]
That is what we currently do :+1:

**Comment by mejariamol** [comment]
@iamareebjamal Yeah. but currently the data load request is called every time when fragment is hosted. That is if user switches between event containing fragments then the request calls will be called repetitively.

This must be fixed to avoid repetitive calls.

**Comment by iamareebjamal** [comment]
Call to network is made only once, all other calls are to database.

**Comment by mejariamol** [comment]
@iamareebjamal true. Sending a PR for fragment persistance
