### ISSUE TITLE
Orga app should allow the organizer to update his/her info from the app.

### ISSUE THREAD

**Issue by ahsan44411** [fossasia/open-event-orga-app#827]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
    
### Feature Request

**Feature Description**

The Application does not allow the organizer to update his profile his/her information.

![screenshot_2018-03-22-19-10-15](https://user-images.githubusercontent.com/30962013/37815487-48ec7912-2e2c-11e8-9a85-2c6219085bb2.png)

Do you want to work on this issue?
Yes

**Comment by iamareebjamal** [comment]
Profile picture issue is already open. Please change the description to profile info

**Comment by ahsan44411** [comment]
Done Sir!. Actually I might need your help on this, like how should I proceed. I was thinking of adding the menu option under the change password.

![screenshot_2018-03-23-11-57-16](https://user-images.githubusercontent.com/30962013/37815686-17b8a090-2e2d-11e8-911c-5eee5da7dc1e.png)

**Comment by iamareebjamal** [comment]
Add a toolbar option

**Comment by ahsan44411** [comment]
Create a new activity which displays the basic info, upon editable text field and an icon on the toolbar to fire that activity? @iamareebjamal

**Comment by ahsan44411** [comment]
I won't be working on this. I will add this in my GSOC 18 proposal.

**Comment by iamareebjamal** [comment]
Hi, working on created issues is very important. You should add the things on our roadmap to your proposal. In fact, we factor contributions in consideration for selection. The more you have contributed, the more chances you have of getting selected. Also, an issue is something we want to be immediately worked upon. You can claim an issue and work on it but you can't halt anyone else to work on it if you aren't because it is not an intellectual property you hold a right upon. This feature was going to be implemented anyway. So I recommend that you work upon it or let anyone else do it for both reasons I mentioned above :smile:

**Comment by ahsan44411** [comment]
Ok I'll start working on it again, sorry. If I have any problem or if I need guidance I'll ask you straight away. Thanks :)

**Comment by AkshayCHD** [comment]
@ahsan44411 are you still working on this issue or can i take it up.

**Comment by iamareebjamal** [comment]
@AkshayCHD Please go ahead

**Comment by ahsan44411** [comment]
No I am, I was busy with my mid term exams during the past two weeks.

**Comment by ahsan44411** [comment]
@AkshayCHD you can take the issue, sorry for wasting your time.

**Comment by AkshayCHD** [comment]
@ahsan44411 no problem :sweat_smile:
